services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # roda northwind.sql na primeira inicialização
    networks:
      - analytics-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d northwind"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com   # use um e-mail válido
      PGADMIN_DEFAULT_PASSWORD: admin
      # Se quiser usar admin@local, libere o domínio:
      # PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '["local"]'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"  # acesso via http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - analytics-net

  dbt:
    build:
      context: .
      dockerfile: Dockerfile    # ajuste se o nome do seu Dockerfile for outro
    working_dir: /app
    volumes:
      - ./:/app
      - ./profiles:/root/.dbt   # monte seu profiles.yml aqui
    environment:
      # DEV (alinha com Postgres do compose)
      DBT_HOST: postgres
      DBT_PORT: "5432"
      DBT_USER: admin
      DBT_PASSWORD: admin
      DBT_DBNAME: northwind
      DBT_SCHEMA: analytics

      # Defaults para evitar Parsing Error (mesmo sem usar PROD agora)
      DB_HOST_PROD: postgres
      DB_PORT_PROD: "5432"
      DB_USER_PROD: admin
      DB_PASSWORD_PROD: admin
      DB_NAME_PROD: northwind
      DB_SCHEMA_PROD: analytics
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - analytics-net
    command: ["bash", "-lc", "dbt debug && tail -f /dev/null"]

volumes:
  pgdata:
  pgadmin_data:

networks:
  analytics-net:
    driver: bridge