services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # roda northwind.sql na primeira inicialização
    networks:
      - analytics-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d northwind"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com   # use um e-mail válido
      PGADMIN_DEFAULT_PASSWORD: admin
      # Se quiser usar admin@local, libere o domínio:
      # PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '["local"]'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"  # acesso via http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - analytics-net

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    working_dir:  /app
    volumes:
      - ./northwind:/app
      - ./profiles:/root/.dbt

    environment:
      # DEV (útil se você alternar para target: dev)
      DBT_HOST: postgres
      DBT_PORT: "5432"
      DBT_USER: admin
      DBT_PASSWORD: admin
      DBT_DBNAME: northwind
      DBT_SCHEMA: analytics
      DBT_THREADS: "4"

      # PROD (deve bater com seu profiles.yml)
      DB_HOST_PROD: postgres
      DB_PORT_PROD: "5432"
      DB_USER_PROD: admin
      DB_PASS_PROD: admin          # ATENÇÃO: agora é PASS (igual ao profiles.yml)
      DB_NAME_PROD: northwind
      DB_SCHEMA_PROD: analytics
      DB_THREADS_PROD: "8"         # incluído para evitar o erro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - analytics-net
    # command: ["bash", "-lc", "dbt debug && tail -f /dev/null"]
    command: ["sleep", "infinity"]
volumes:
  pgdata:
  pgadmin_data:

networks:
  analytics-net:
    driver: bridge