northwind:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      password: "{{ env_var('DB_PASS') }}"
      port: "{{ env_var('DB_PORT') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      threads: "{{ env_var('DB_THREADS') }}"
      type: "{{ env_var('DB_TYPE') }}"
      user: "{{ env_var('DB_USER') }}"
  target: dev
