# dbt_project.yml
name: 'northwind'
version: '1.0.0'

# Perfil do dbt que deve existir em profiles.yml
profile: 'northwind'

# Pastas do projeto
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

# Pastas removidas por `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configurações globais
quoting:
  database: false
  schema: false
  identifier: false

# Variáveis globais (adicione se precisar em macros/models)
vars: {}

# Seeds: controle de cabeçalho, tipos e schema
seeds:
  +schema: "seed"
  +quote_columns: false
  northwind:
    +enabled: true
    # Exemplo de tipos por coluna (ajuste conforme suas seeds)
    # customers.csv:
    #   +column_types:
    #     customer_id: varchar
    #     company_name: varchar

# Snapshots: esquema dedicado
snapshots:
  +schema: "snapshot"

# Tests: configurações padrão
tests:
  +severity: "ERROR"

# Documentação: habilita persistência de docs (se usar docs blocks e exposures)
# Você já tem docs-paths; opcionalmente defina configs adicionais se quiser
# dispatch, packages, exposures podem ser adicionados conforme crescer o projeto

# Modelos por camada
models:
  northwind:

    # Camada bronze (raw): views
    raw:
      +materialized: view
      +tags: ["bronze", "raw"]
      +docs:
        node_color: "#cd7f32"

    # Camada prata (staging): views
    staging:
      +materialized: view
      +tags: ["silver", "staging"]
      +docs:
        node_color: "#c0c0c0"
      # Convenções úteis de nomes/alias (opcional)
      # +alias: "stg__{{ this.name }}"

    # Camada ouro (reports): tables no schema gold
    reports:
      +schema: "gold"
      +materialized: table
      +tags: ["gold", "reports"]
      +docs:
        node_color: "#e6b530"
      # Particionamento/clusterização específicos por warehouse podem ser adicionados
      # via configs por modelo quando necessário
