name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-dbt-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies from requirements.txt
      run: pip install -r northwind/requirements.txt

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "
        northwind:
          target: prod
          outputs:
            prod:
              type: postgres
              host: ${{ secrets.DB_HOST_PROD }}
              port: ${{ secrets.DB_PORT_PROD }}
              user: ${{ secrets.DB_USER_PROD }}
              password: ${{ secrets.DB_PASS_PROD }}
              dbname: ${{ secrets.DB_NAME_PROD }}
              schema: ${{ secrets.DB_SCHEMA_PROD }}
              threads: 4 # Threads pode ser um valor fixo aqui
        " > ~/.dbt/profiles.yml

    - name: Generate dbt docs
      run: |
        cd northwind
        dbt docs generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Este token é gerado automaticamente pelo GitHub Actions.
        # Você não precisa criar um segredo GH_PAT para este uso básico.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./northwind/target
        # Opcional: se o seu site não estiver na raiz, descomente a linha abaixo
        # publish_branch: gh-pages